<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           estandards
    date            AdmDateInserted
    date            AdmDateModified
    table           guid
      text short      AdmGUIDIsPreferred
      text short      AdmGUIDType
      text short      AdmGUIDValue
    end
    text short      AdmImportIdentifier
    text short      AdmInsertedBy
    text short      AdmModifiedBy
    text long       AdmOriginalData
    text short      AdmPublishWebNoPassword
    text short      AdmPublishWebPassword
    text short      AdmSystemIdentifier
    time            AdmTimeInserted
    time            AdmTimeModified
    table           BetweenValue_nesttab
      table           BetweenValue_nesttab_inner
        text short      BetweenValue
      end
    end
    text short      CollapseEmptyValues
    table           DefinedTerm_tab
      text short      DefinedTerm
    end
    table           DefinitionsRef_tab
      integer         definitionsRef_tab_irn
    end
    text long       Errors
    text long       ExtendedData
    text short      ExtractName
    table           Field_tab
      text short      Field
    end
    table           Format_tab
      text short      Format
    end
    table           FormatSeparator_tab
      text short      FormatSeparator
    end
    text short      FormatSpecifier
    table           FormatType_tab
      text short      FormatType
    end
    integer         irn
    text short      Module
    table           NestedSeparator_tab
      text short      NestedSeparator
    end
    text long       NotNotes
    table           note
      table           NteAttributedToRef_nesttab
        integer         NteAttributedToRef
      end
      table           NteBibliographyRef_nesttab
        integer         NteBibliographyRef
      end
      date            NteDate
      text long       NteText
      text short      NteType
    end
    text short      RecordType
    text short      RemoveDuplicateValues
    table           RowInclusion_tab
      text short      RowInclusion
    end
    text long       Script
    table           SecDepartment_tab
      text short      SecDepartment
    end
    text short      SecRecordStatus
    text short      StandardName
    text short      StandardVersion
    text short      Status
    text short      SummaryData
    text short      Term
    text long       TermFormatString
    text long       TermURI
    text short      TypeOfWhere
    table           Value_nesttab
      table           Value_nesttab_inner
        text short      Value
      end
    end
    table           where
      table           WhereCondition_nesttab
        text short      WhereCondition
      end
      table           WhereField_nesttab
        text short      WhereField
      end
      table           WhereKind_nesttab
        text short      WhereKind
      end
      table           WhereType_nesttab
        text short      WhereType
      end
    end
    text short      WhereOperator
  end
?>
<!-- Data -->
<table name="estandards">

  <!-- Row 1 -->
  <tuple>
    <atom name="AdmDateInserted">2022-09-07</atom>
    <atom name="AdmDateModified">2022-11-08</atom>
    <atom name="AdmImportIdentifier">ecatalog - edarwincore: row[52]</atom>
    <atom name="AdmInsertedBy">KE EMu Administrator</atom>
    <atom name="AdmModifiedBy">KE EMu Administrator</atom>
    <atom name="AdmOriginalData"></atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="AdmPublishWebPassword">No</atom>
    <atom name="AdmSystemIdentifier"></atom>
    <atom name="AdmTimeInserted">23:47:13</atom>
    <atom name="AdmTimeModified">13:48:34</atom>
    <table name="BetweenValue_nesttab">
    </table>
    <atom name="CollapseEmptyValues">Yes</atom>
    <atom name="Errors"></atom>
    <atom name="ExtendedData">184
Term Definition [Active] dwc:georeferenceSources - Darwin Core 2022-11-08 (String)</atom>
    <atom name="ExtractName"></atom>
    <table name="Field_tab">
      <tuple>
        <atom name="Field">ColCollectionEventRef.ecollectionevents.ColSiteRef.esites.LatDetSource_tab</atom>
      </tuple>
    </table>
    <atom name="FormatSpecifier">String</atom>
    <table name="FormatType_tab">
      <tuple>
        <atom name="FormatType">Text</atom>
      </tuple>
    </table>
    <atom name="irn">184</atom>
    <atom name="Module">ecatalogue</atom>
    <table name="NestedSeparator_tab">
      <tuple>
        <atom name="NestedSeparator">|</atom>
      </tuple>
    </table>
    <atom name="NotNotes"></atom>
    <atom name="RecordType">Term Definition</atom>
    <atom name="RemoveDuplicateValues">Yes</atom>
    <table name="RowInclusion_tab">
      <tuple>
        <atom name="RowInclusion">All Rows</atom>
      </tuple>
    </table>
    <atom name="Script"></atom>
    <atom name="SecRecordStatus"></atom>
    <atom name="StandardName">Darwin Core</atom>
    <atom name="StandardVersion">2022-11-08</atom>
    <atom name="Status">Active</atom>
    <atom name="SummaryData">Term Definition [Active] dwc:georeferenceSources - Darwin Core 2022-11-08 (String)</atom>
    <atom name="Term">dwc:georeferenceSources</atom>
    <atom name="TermFormatString">%s</atom>
    <atom name="TermURI">http://rs.tdwg.org/dwc/terms/georeferenceSources</atom>
    <atom name="TypeOfWhere"></atom>
    <table name="Value_nesttab">
      <tuple>
        <table name="Value_nesttab_inner">
          <tuple>
            <atom name="Value">Yes</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <table name="where">
      <tuple>
        <table name="WhereCondition_nesttab">
          <tuple>
            <atom name="WhereCondition">Equals</atom>
          </tuple>
        </table>
        <table name="WhereField_nesttab">
          <tuple>
            <atom name="WhereField">ColCollectionEventRef.ecollectionevents.ColSiteRef.esites.LatPreferred_tab</atom>
          </tuple>
        </table>
        <table name="WhereKind_nesttab">
          <tuple>
            <atom name="WhereKind">Table</atom>
          </tuple>
        </table>
        <table name="WhereType_nesttab">
          <tuple>
            <atom name="WhereType">Text</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="WhereOperator"></atom>
  </tuple>

  <!-- Row 2 -->
  <tuple>
    <atom name="AdmDateInserted">2022-09-07</atom>
    <atom name="AdmDateModified">2022-11-08</atom>
    <atom name="AdmImportIdentifier">ecatalog - edarwincore: row[51]</atom>
    <atom name="AdmInsertedBy">KE EMu Administrator</atom>
    <atom name="AdmModifiedBy">KE EMu Administrator</atom>
    <atom name="AdmOriginalData"></atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="AdmPublishWebPassword">No</atom>
    <atom name="AdmSystemIdentifier"></atom>
    <atom name="AdmTimeInserted">23:47:13</atom>
    <atom name="AdmTimeModified">13:48:34</atom>
    <table name="BetweenValue_nesttab">
    </table>
    <atom name="CollapseEmptyValues">Yes</atom>
    <atom name="Errors"></atom>
    <atom name="ExtendedData">183
Term Definition [Active] dwc:georeferencedDate - Darwin Core 2022-11-08 (String)</atom>
    <atom name="ExtractName"></atom>
    <table name="Field_tab">
      <tuple>
        <atom name="Field">ColCollectionEventRef.ecollectionevents.ColSiteRef.esites.LatDetDate0</atom>
      </tuple>
    </table>
    <atom name="FormatSpecifier">String</atom>
    <table name="FormatType_tab">
      <tuple>
        <atom name="FormatType">Date</atom>
      </tuple>
    </table>
    <atom name="irn">183</atom>
    <atom name="Module">ecatalogue</atom>
    <table name="NestedSeparator_tab">
      <tuple>
        <atom name="NestedSeparator">|</atom>
      </tuple>
    </table>
    <atom name="NotNotes"></atom>
    <atom name="RecordType">Term Definition</atom>
    <atom name="RemoveDuplicateValues">Yes</atom>
    <table name="RowInclusion_tab">
      <tuple>
        <atom name="RowInclusion">All Rows</atom>
      </tuple>
    </table>
    <atom name="Script"></atom>
    <atom name="SecRecordStatus"></atom>
    <atom name="StandardName">Darwin Core</atom>
    <atom name="StandardVersion">2022-11-08</atom>
    <atom name="Status">Active</atom>
    <atom name="SummaryData">Term Definition [Active] dwc:georeferencedDate - Darwin Core 2022-11-08 (String)</atom>
    <atom name="Term">dwc:georeferencedDate</atom>
    <atom name="TermFormatString">%s</atom>
    <atom name="TermURI">http://rs.tdwg.org/dwc/terms/georeferencedDate</atom>
    <atom name="TypeOfWhere">Row Select</atom>
    <table name="Value_nesttab">
      <tuple>
        <table name="Value_nesttab_inner">
          <tuple>
            <atom name="Value">Yes</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <table name="where">
      <tuple>
        <table name="WhereCondition_nesttab">
          <tuple>
            <atom name="WhereCondition">Equals</atom>
          </tuple>
        </table>
        <table name="WhereField_nesttab">
          <tuple>
            <atom name="WhereField">ColCollectionEventRef.ecollectionevents.ColSiteRef.esites.LatPreferred_tab</atom>
          </tuple>
        </table>
        <table name="WhereKind_nesttab">
          <tuple>
            <atom name="WhereKind">Table</atom>
          </tuple>
        </table>
        <table name="WhereType_nesttab">
          <tuple>
            <atom name="WhereType">Text</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="WhereOperator">AND</atom>
  </tuple>

  <!-- Row 3 -->
  <tuple>
    <atom name="AdmDateInserted">2022-09-07</atom>
    <atom name="AdmDateModified">2022-11-08</atom>
    <atom name="AdmImportIdentifier">ecatalog - edarwincore: row[63]</atom>
    <atom name="AdmInsertedBy">KE EMu Administrator</atom>
    <atom name="AdmModifiedBy">KE EMu Administrator</atom>
    <atom name="AdmOriginalData"></atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="AdmPublishWebPassword">No</atom>
    <atom name="AdmSystemIdentifier"></atom>
    <atom name="AdmTimeInserted">23:47:13</atom>
    <atom name="AdmTimeModified">13:48:34</atom>
    <table name="BetweenValue_nesttab">
    </table>
    <atom name="CollapseEmptyValues">Yes</atom>
    <atom name="Errors"></atom>
    <atom name="ExtendedData">195
Term Definition [Active] dwc:informationWithheld - Darwin Core 2022-11-08 (String)</atom>
    <atom name="ExtractName"></atom>
    <table name="Field_tab">
      <tuple>
        <atom name="Field">NotFisNotes0</atom>
      </tuple>
    </table>
    <atom name="FormatSpecifier">String</atom>
    <table name="FormatType_tab">
      <tuple>
        <atom name="FormatType">Text</atom>
      </tuple>
    </table>
    <atom name="irn">195</atom>
    <atom name="Module">ecatalogue</atom>
    <atom name="NotNotes"></atom>
    <atom name="RecordType">Term Definition</atom>
    <atom name="RemoveDuplicateValues">Yes</atom>
    <table name="RowInclusion_tab">
      <tuple>
        <atom name="RowInclusion">First Row</atom>
      </tuple>
    </table>
    <atom name="Script"></atom>
    <atom name="SecRecordStatus"></atom>
    <atom name="StandardName">Darwin Core</atom>
    <atom name="StandardVersion">2022-11-08</atom>
    <atom name="Status">Active</atom>
    <atom name="SummaryData">Term Definition [Active] dwc:informationWithheld - Darwin Core 2022-11-08 (String)</atom>
    <atom name="Term">dwc:informationWithheld</atom>
    <atom name="TermFormatString">%s</atom>
    <atom name="TermURI">http://rs.tdwg.org/dwc/terms/informationWithheld</atom>
    <atom name="TypeOfWhere">Row Select</atom>
    <table name="Value_nesttab">
      <tuple>
        <table name="Value_nesttab_inner">
          <tuple>
            <atom name="Value">DwC Information Withheld</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <table name="where">
      <tuple>
        <table name="WhereCondition_nesttab">
          <tuple>
            <atom name="WhereCondition">Equals</atom>
          </tuple>
        </table>
        <table name="WhereField_nesttab">
          <tuple>
            <atom name="WhereField">NotKind_tab</atom>
          </tuple>
        </table>
        <table name="WhereKind_nesttab">
          <tuple>
            <atom name="WhereKind">Table</atom>
          </tuple>
        </table>
        <table name="WhereType_nesttab">
          <tuple>
            <atom name="WhereType">Text</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="WhereOperator"></atom>
  </tuple>

  <!-- Row 4 -->
  <tuple>
    <atom name="AdmDateInserted">2022-09-07</atom>
    <atom name="AdmDateModified">2022-11-08</atom>
    <atom name="AdmImportIdentifier">ecatalog - edarwincore: row[66]</atom>
    <atom name="AdmInsertedBy">KE EMu Administrator</atom>
    <atom name="AdmModifiedBy">KE EMu Administrator</atom>
    <atom name="AdmOriginalData"></atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="AdmPublishWebPassword">No</atom>
    <atom name="AdmSystemIdentifier"></atom>
    <atom name="AdmTimeInserted">23:47:13</atom>
    <atom name="AdmTimeModified">13:48:34</atom>
    <table name="BetweenValue_nesttab">
    </table>
    <atom name="CollapseEmptyValues">Yes</atom>
    <atom name="Errors"></atom>
    <atom name="ExtendedData">198
Term Definition [Active] dwc:island - Darwin Core 2022-11-08</atom>
    <atom name="ExtractName"></atom>
    <table name="Field_tab">
      <tuple>
        <atom name="Field">ColCollectionEventRef.ecollectionevents.ColSiteRef.esites.LocIslandName</atom>
      </tuple>
    </table>
    <atom name="FormatSpecifier"></atom>
    <table name="FormatType_tab">
      <tuple>
        <atom name="FormatType">Text</atom>
      </tuple>
    </table>
    <atom name="irn">198</atom>
    <atom name="Module">ecatalogue</atom>
    <atom name="NotNotes"></atom>
    <atom name="RecordType">Term Definition</atom>
    <atom name="RemoveDuplicateValues">Yes</atom>
    <atom name="Script"></atom>
    <atom name="SecRecordStatus"></atom>
    <atom name="StandardName">Darwin Core</atom>
    <atom name="StandardVersion">2022-11-08</atom>
    <atom name="Status">Active</atom>
    <atom name="SummaryData">Term Definition [Active] dwc:island - Darwin Core 2022-11-08</atom>
    <atom name="Term">dwc:island</atom>
    <atom name="TermFormatString">%s</atom>
    <atom name="TermURI">http://rs.tdwg.org/dwc/terms/island</atom>
    <atom name="TypeOfWhere"></atom>
    <table name="Value_nesttab">
    </table>
    <atom name="WhereOperator"></atom>
  </tuple>

  <!-- Row 5 -->
  <tuple>
    <atom name="AdmDateInserted">2022-09-07</atom>
    <atom name="AdmDateModified">2022-11-08</atom>
    <atom name="AdmImportIdentifier">ecatalog - edarwincore: row[68]</atom>
    <atom name="AdmInsertedBy">KE EMu Administrator</atom>
    <atom name="AdmModifiedBy">KE EMu Administrator</atom>
    <atom name="AdmOriginalData"></atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="AdmPublishWebPassword">No</atom>
    <atom name="AdmSystemIdentifier"></atom>
    <atom name="AdmTimeInserted">23:47:13</atom>
    <atom name="AdmTimeModified">13:48:34</atom>
    <table name="BetweenValue_nesttab">
    </table>
    <atom name="CollapseEmptyValues">Yes</atom>
    <atom name="Errors"></atom>
    <atom name="ExtendedData">200
Term Definition [Active] dwc:kingdom - Darwin Core 2022-11-08</atom>
    <atom name="ExtractName"></atom>
    <table name="Field_tab">
      <tuple>
        <atom name="Field">IdeTaxonRef_tab.etaxonomy.ClaKingdom</atom>
      </tuple>
    </table>
    <atom name="FormatSpecifier"></atom>
    <table name="FormatType_tab">
      <tuple>
        <atom name="FormatType">Text</atom>
      </tuple>
    </table>
    <atom name="irn">200</atom>
    <atom name="Module">ecatalogue</atom>
    <atom name="NotNotes"></atom>
    <atom name="RecordType">Term Definition</atom>
    <atom name="RemoveDuplicateValues">Yes</atom>
    <atom name="Script"></atom>
    <atom name="SecRecordStatus"></atom>
    <atom name="StandardName">Darwin Core</atom>
    <atom name="StandardVersion">2022-11-08</atom>
    <atom name="Status">Active</atom>
    <atom name="SummaryData">Term Definition [Active] dwc:kingdom - Darwin Core 2022-11-08</atom>
    <atom name="Term">dwc:kingdom</atom>
    <atom name="TermFormatString">%s</atom>
    <atom name="TermURI">http://rs.tdwg.org/dwc/terms/kingdom</atom>
    <atom name="TypeOfWhere"></atom>
    <table name="Value_nesttab">
    </table>
    <atom name="WhereOperator"></atom>
  </tuple>

  <!-- Row 6 -->
  <tuple>
    <atom name="AdmDateInserted">2022-09-07</atom>
    <atom name="AdmDateModified">2022-11-08</atom>
    <atom name="AdmImportIdentifier">ecatalog - edarwincore: row[76]</atom>
    <atom name="AdmInsertedBy">KE EMu Administrator</atom>
    <atom name="AdmModifiedBy">KE EMu Administrator</atom>
    <atom name="AdmOriginalData"></atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="AdmPublishWebPassword">No</atom>
    <atom name="AdmSystemIdentifier"></atom>
    <atom name="AdmTimeInserted">23:47:13</atom>
    <atom name="AdmTimeModified">13:48:34</atom>
    <table name="BetweenValue_nesttab">
    </table>
    <atom name="CollapseEmptyValues">Yes</atom>
    <atom name="Errors"></atom>
    <atom name="ExtendedData">208
Term Definition [Active] dwc:lifestage - Darwin Core 2022-11-08 (String)</atom>
    <atom name="ExtractName"></atom>
    <table name="Field_tab">
      <tuple>
        <atom name="Field">PheStage_tab</atom>
      </tuple>
    </table>
    <atom name="FormatSpecifier">String</atom>
    <table name="FormatType_tab">
      <tuple>
        <atom name="FormatType">Text</atom>
      </tuple>
    </table>
    <atom name="irn">208</atom>
    <atom name="Module">ecatalogue</atom>
    <table name="NestedSeparator_tab">
      <tuple>
        <atom name="NestedSeparator">|</atom>
      </tuple>
    </table>
    <atom name="NotNotes"></atom>
    <atom name="RecordType">Term Definition</atom>
    <atom name="RemoveDuplicateValues">Yes</atom>
    <table name="RowInclusion_tab">
      <tuple>
        <atom name="RowInclusion">All Rows</atom>
      </tuple>
    </table>
    <atom name="Script"></atom>
    <atom name="SecRecordStatus"></atom>
    <atom name="StandardName">Darwin Core</atom>
    <atom name="StandardVersion">2022-11-08</atom>
    <atom name="Status">Active</atom>
    <atom name="SummaryData">Term Definition [Active] dwc:lifestage - Darwin Core 2022-11-08 (String)</atom>
    <atom name="Term">dwc:lifestage</atom>
    <atom name="TermFormatString"></atom>
    <atom name="TermURI">http://rs.tdwg.org/dwc/terms/lifeStage</atom>
    <atom name="TypeOfWhere"></atom>
    <table name="Value_nesttab">
    </table>
    <atom name="WhereOperator"></atom>
  </tuple>

  <!-- Row 7 -->
  <tuple>
    <atom name="AdmDateInserted">2022-09-07</atom>
    <atom name="AdmDateModified">2022-11-08</atom>
    <atom name="AdmImportIdentifier">ecatalog - edarwincore: row[79]</atom>
    <atom name="AdmInsertedBy">KE EMu Administrator</atom>
    <atom name="AdmModifiedBy">KE EMu Administrator</atom>
    <atom name="AdmOriginalData"></atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="AdmPublishWebPassword">No</atom>
    <atom name="AdmSystemIdentifier"></atom>
    <atom name="AdmTimeInserted">23:47:13</atom>
    <atom name="AdmTimeModified">13:48:34</atom>
    <table name="BetweenValue_nesttab">
    </table>
    <atom name="CollapseEmptyValues">Yes</atom>
    <atom name="Errors"></atom>
    <atom name="ExtendedData">211
Term Definition [Active] dwc:locationID - Darwin Core 2022-11-08 (String)</atom>
    <atom name="ExtractName"></atom>
    <table name="Field_tab">
      <tuple>
        <atom name="Field">ColCollectionEventRef.ecollectionevents.ColSiteRef.esites.AdmGUIDValue_tab</atom>
      </tuple>
    </table>
    <atom name="FormatSpecifier">String</atom>
    <table name="FormatType_tab">
      <tuple>
        <atom name="FormatType">Text</atom>
      </tuple>
    </table>
    <atom name="irn">211</atom>
    <atom name="Module">ecatalogue</atom>
    <atom name="NotNotes"></atom>
    <atom name="RecordType">Term Definition</atom>
    <atom name="RemoveDuplicateValues">Yes</atom>
    <atom name="Script"></atom>
    <atom name="SecRecordStatus"></atom>
    <atom name="StandardName">Darwin Core</atom>
    <atom name="StandardVersion">2022-11-08</atom>
    <atom name="Status">Active</atom>
    <atom name="SummaryData">Term Definition [Active] dwc:locationID - Darwin Core 2022-11-08 (String)</atom>
    <atom name="Term">dwc:locationID</atom>
    <atom name="TermFormatString">%s</atom>
    <atom name="TermURI">http://rs.tdwg.org/dwc/terms/locationID</atom>
    <atom name="TypeOfWhere">Boolean</atom>
    <table name="Value_nesttab">
      <tuple>
        <table name="Value_nesttab_inner">
          <tuple>
            <atom name="Value">UUID4</atom>
          </tuple>
          <tuple>
            <atom name="Value">No</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <table name="where">
      <tuple>
        <table name="WhereCondition_nesttab">
          <tuple>
            <atom name="WhereCondition">Equals</atom>
          </tuple>
          <tuple>
            <atom name="WhereCondition">Equals</atom>
          </tuple>
        </table>
        <table name="WhereField_nesttab">
          <tuple>
            <atom name="WhereField">ColCollectionEventRef.ecollectionevents.ColSiteRef.esites.AdmGUIDType_tab</atom>
          </tuple>
          <tuple>
            <atom name="WhereField">ColCollectionEventRef.ecollectionevents.ColSiteRef.esites.AdmGUIDIsPreferred_tab</atom>
          </tuple>
        </table>
        <table name="WhereKind_nesttab">
          <tuple>
            <atom name="WhereKind">Table</atom>
          </tuple>
          <tuple>
            <atom name="WhereKind">Table</atom>
          </tuple>
        </table>
        <table name="WhereType_nesttab">
          <tuple>
            <atom name="WhereType">Text</atom>
          </tuple>
          <tuple>
            <atom name="WhereType">Text</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="WhereOperator">AND</atom>
  </tuple>

  <!-- Row 8 -->
  <tuple>
    <atom name="AdmDateInserted">2022-09-07</atom>
    <atom name="AdmDateModified">2022-11-08</atom>
    <atom name="AdmImportIdentifier">ecatalog - edarwincore: row[82]</atom>
    <atom name="AdmInsertedBy">KE EMu Administrator</atom>
    <atom name="AdmModifiedBy">KE EMu Administrator</atom>
    <atom name="AdmOriginalData"></atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="AdmPublishWebPassword">No</atom>
    <atom name="AdmSystemIdentifier"></atom>
    <atom name="AdmTimeInserted">23:47:13</atom>
    <atom name="AdmTimeModified">13:48:34</atom>
    <table name="BetweenValue_nesttab">
    </table>
    <atom name="CollapseEmptyValues">Yes</atom>
    <atom name="Errors"></atom>
    <atom name="ExtendedData">214
Term Definition [Active] dwc:maximumDepthInMeters - Darwin Core 2022-11-08 (String)</atom>
    <atom name="ExtractName"></atom>
    <table name="Field_tab">
      <tuple>
        <atom name="Field">ColCollectionEventRef.ecollectionevents.AquDepthToMet</atom>
      </tuple>
      <tuple>
        <atom name="Field">ColCollectionEventRef.ecollectionevents.AquDepthFromMet</atom>
      </tuple>
    </table>
    <atom name="FormatSpecifier">String</atom>
    <table name="FormatType_tab">
      <tuple>
        <atom name="FormatType">Float</atom>
      </tuple>
      <tuple>
        <atom name="FormatType">Float</atom>
      </tuple>
    </table>
    <atom name="irn">214</atom>
    <atom name="Module">ecatalogue</atom>
    <atom name="NotNotes"></atom>
    <atom name="RecordType">Term Definition</atom>
    <atom name="RemoveDuplicateValues">Yes</atom>
    <atom name="Script"></atom>
    <atom name="SecRecordStatus"></atom>
    <atom name="StandardName">Darwin Core</atom>
    <atom name="StandardVersion">2022-11-08</atom>
    <atom name="Status">Active</atom>
    <atom name="SummaryData">Term Definition [Active] dwc:maximumDepthInMeters - Darwin Core 2022-11-08 (String)</atom>
    <atom name="Term">dwc:maximumDepthInMeters</atom>
    <atom name="TermFormatString">%s</atom>
    <atom name="TermURI">http://rs.tdwg.org/dwc/terms/maximumDepthInMeters</atom>
    <atom name="TypeOfWhere"></atom>
    <table name="Value_nesttab">
    </table>
    <table name="where">
      <tuple>
        <table name="WhereCondition_nesttab">
          <tuple>
            <atom name="WhereCondition">Is Not Null</atom>
          </tuple>
        </table>
        <table name="WhereField_nesttab">
          <tuple>
            <atom name="WhereField">ColCollectionEventRef.ecollectionevents.AquDepthToMet</atom>
          </tuple>
        </table>
        <table name="WhereKind_nesttab">
          <tuple>
            <atom name="WhereKind">Atom</atom>
          </tuple>
        </table>
        <table name="WhereType_nesttab">
          <tuple>
            <atom name="WhereType">Float</atom>
          </tuple>
        </table>
      </tuple>
      <tuple>
        <table name="WhereCondition_nesttab">
          <tuple>
            <atom name="WhereCondition">Is Null</atom>
          </tuple>
        </table>
        <table name="WhereField_nesttab">
          <tuple>
            <atom name="WhereField">ColCollectionEventRef.ecollectionevents.AquDepthToMet</atom>
          </tuple>
        </table>
        <table name="WhereKind_nesttab">
          <tuple>
            <atom name="WhereKind">Atom</atom>
          </tuple>
        </table>
        <table name="WhereType_nesttab">
          <tuple>
            <atom name="WhereType">Float</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="WhereOperator"></atom>
  </tuple>

  <!-- Row 9 -->
  <tuple>
    <atom name="AdmDateInserted">2022-09-07</atom>
    <atom name="AdmDateModified">2022-11-08</atom>
    <atom name="AdmImportIdentifier">ecatalog - edarwincore: row[83]</atom>
    <atom name="AdmInsertedBy">KE EMu Administrator</atom>
    <atom name="AdmModifiedBy">KE EMu Administrator</atom>
    <atom name="AdmOriginalData"></atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="AdmPublishWebPassword">No</atom>
    <atom name="AdmSystemIdentifier"></atom>
    <atom name="AdmTimeInserted">23:47:13</atom>
    <atom name="AdmTimeModified">13:48:34</atom>
    <table name="BetweenValue_nesttab">
    </table>
    <atom name="CollapseEmptyValues">Yes</atom>
    <atom name="Errors"></atom>
    <atom name="ExtendedData">215
Term Definition [Active] dwc:maximumElevationInMeters - Darwin Core 2022-11-08 (String)</atom>
    <atom name="ExtractName"></atom>
    <table name="Field_tab">
      <tuple>
        <atom name="Field">ColCollectionEventRef.ecollectionevents.ColSiteRef.esites.LocElevationASLToMt</atom>
      </tuple>
      <tuple>
        <atom name="Field">ColCollectionEventRef.ecollectionevents.ColSiteRef.esites.LocElevationASLFromMt</atom>
      </tuple>
    </table>
    <atom name="FormatSpecifier">String</atom>
    <table name="FormatType_tab">
      <tuple>
        <atom name="FormatType">Float</atom>
      </tuple>
      <tuple>
        <atom name="FormatType">Float</atom>
      </tuple>
    </table>
    <atom name="irn">215</atom>
    <atom name="Module">ecatalogue</atom>
    <atom name="NotNotes"></atom>
    <atom name="RecordType">Term Definition</atom>
    <atom name="RemoveDuplicateValues">Yes</atom>
    <atom name="Script"></atom>
    <atom name="SecRecordStatus"></atom>
    <atom name="StandardName">Darwin Core</atom>
    <atom name="StandardVersion">2022-11-08</atom>
    <atom name="Status">Active</atom>
    <atom name="SummaryData">Term Definition [Active] dwc:maximumElevationInMeters - Darwin Core 2022-11-08 (String)</atom>
    <atom name="Term">dwc:maximumElevationInMeters</atom>
    <atom name="TermFormatString">%s</atom>
    <atom name="TermURI">http://rs.tdwg.org/dwc/terms/maximumElevationInMeters</atom>
    <atom name="TypeOfWhere"></atom>
    <table name="Value_nesttab">
    </table>
    <table name="where">
      <tuple>
        <table name="WhereCondition_nesttab">
          <tuple>
            <atom name="WhereCondition">Is Not Null</atom>
          </tuple>
        </table>
        <table name="WhereField_nesttab">
          <tuple>
            <atom name="WhereField">ColCollectionEventRef.ecollectionevents.ColSiteRef.esites.LocElevationASLToMt</atom>
          </tuple>
        </table>
        <table name="WhereKind_nesttab">
          <tuple>
            <atom name="WhereKind">Atom</atom>
          </tuple>
        </table>
        <table name="WhereType_nesttab">
          <tuple>
            <atom name="WhereType">Float</atom>
          </tuple>
        </table>
      </tuple>
      <tuple>
        <table name="WhereCondition_nesttab">
          <tuple>
            <atom name="WhereCondition">Is Null</atom>
          </tuple>
        </table>
        <table name="WhereField_nesttab">
          <tuple>
            <atom name="WhereField">ColCollectionEventRef.ecollectionevents.ColSiteRef.esites.LocElevationASLToMt</atom>
          </tuple>
        </table>
        <table name="WhereKind_nesttab">
          <tuple>
            <atom name="WhereKind">Atom</atom>
          </tuple>
        </table>
        <table name="WhereType_nesttab">
          <tuple>
            <atom name="WhereType">Float</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="WhereOperator"></atom>